import type { PostWithAuthor, User, CommentWithAuthor } from './definitions';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alisha Sharma',
    email: 'alisha.s@example.com',
    password: 'hashed_password',
    role: 'ALUMNI',
    bio: 'Software Engineer at Google. Passionate about AI and machine learning. Class of 2018.',
    profileImage: 'https://picsum.photos/seed/user1/200/200',
    course: 'Computer Science',
    batch: 2018,
    profession: 'Software Engineer @ Google',
    createdAt: new Date('2024-01-10T10:00:00Z'),
  },
  {
    id: '2',
    name: 'Rohan Verma',
    email: 'rohan@example.com',
    password: 'hashed_password',
    role: 'STUDENT',
    bio: 'Final year student, exploring opportunities in web development. Eager to connect with alumni!',
    profileImage: 'https://picsum.photos/seed/user2/200/200',
    course: 'Information Technology',
    batch: 2025,
    profession: null,
    createdAt: new Date('2024-07-15T11:30:00Z'),
  },
  {
    id: '3',
    name: 'Dr. Priya Singh',
    email: 'priya.s@example.com',
    password: 'hashed_password',
    role: 'ADMIN',
    bio: 'Professor, Department of Computer Science. Helping students bridge the gap between academia and industry.',
    profileImage: 'https://picsum.photos/seed/user3/200/200',
    course: 'Computer Science',
    batch: null,
    profession: 'Professor',
    createdAt: new Date('2024-01-01T09:00:00Z'),
  },
   {
    id: '4',
    name: 'Vikram Mehta',
    email: 'vikram.m@example.com',
    password: 'hashed_password',
    role: 'ALUMNI',
    bio: 'Product Manager at Microsoft. Always happy to chat about product, strategy, and career growth.',
    profileImage: 'https://picsum.photos/seed/user4/200/200',
    course: 'Business Administration',
    batch: 2016,
    profession: 'Product Manager @ Microsoft',
    createdAt: new Date('2024-06-22T18:45:00Z'),
  },
   {
    id: '5',
    name: 'Sneha Reddy',
    email: 'sneha.r@example.com',
    password: 'hashed_password',
    role: 'STUDENT',
    bio: 'Aspiring data scientist. Looking for internships and projects in the data space.',
    profileImage: 'https://picsum.photos/seed/user5/200/200',
    course: 'Data Science',
    batch: 2026,
    profession: null,
    createdAt: new Date('2024-07-28T12:10:00Z'),
  }
];

export const mockPosts: PostWithAuthor[] = [
  {
    id: 'post1',
    title: 'Internship Opportunity at Google',
    content: "Hey everyone! We have a few openings for summer interns on our Cloud AI team. It's a great opportunity to work on cutting-edge technology. Feel free to DM me for details. #internship #google #ai",
    imageUrl: 'https://picsum.photos/seed/post1/800/400',
    authorId: '1',
    createdAt: new Date('2024-07-28T14:00:00Z'),
    author: mockUsers[0],
    _count: { likes: 128, comments: 12 },
  },
  {
    id: 'post2',
    title: 'Looking for Project Guidance',
    content: "Hi seniors! I'm working on my final year project on a MERN stack application and would love some guidance on implementing real-time notifications. Any help would be appreciated! #webdev #mern #projecthelp",
    imageUrl: null,
    authorId: '2',
    createdAt: new Date('2024-07-26T09:25:00Z'),
    author: mockUsers[1],
    _count: { likes: 45, comments: 8 },
  },
  {
    id: 'post3',
    title: 'Annual Alumni Meet 2024',
    content: "We are excited to announce the Annual Alumni Meet on August 15th, 2024. It's a fantastic chance to reconnect with old friends and make new connections. RSVP link in the college portal. See you there! #alumnimeet #networking",
    imageUrl: 'https://picsum.photos/seed/post3/800/400',
    authorId: '3',
    createdAt: new Date('2024-07-25T18:00:00Z'),
    author: mockUsers[2],
    _count: { likes: 250, comments: 42 },
  },
  {
    id: 'post4',
    title: 'Product Management AMA',
    content: "I'm hosting an 'Ask Me Anything' session this Friday about breaking into Product Management. If you're a student or recent grad interested in the field, join in! #productmanagement #career #ama",
    imageUrl: 'https://picsum.photos/seed/post4/800/400',
    authorId: '4',
    createdAt: new Date('2024-07-29T11:00:00Z'),
    author: mockUsers[3],
    _count: { likes: 180, comments: 25 },
  },
];

export const mockComments: CommentWithAuthor[] = [
    {
        id: 'comment1',
        text: 'This sounds amazing! I will definitely apply.',
        authorId: '2',
        postId: 'post1',
        createdAt: new Date('2024-07-28T15:00:00Z'),
        author: mockUsers[1],
    },
    {
        id: 'comment2',
        text: 'Great initiative Alisha. Happy to see our alumni doing so well.',
        authorId: '3',
        postId: 'post1',
        createdAt: new Date('2024-07-28T16:30:00Z'),
        author: mockUsers[2],
    },
    {
        id: 'comment3',
        text: "Hey Rohan, have you tried looking into Socket.io? It's pretty straightforward for real-time features.",
        authorId: '1',
        postId: 'post2',
        createdAt: new Date('2024-07-26T10:00:00Z'),
        author: mockUsers[0],
    },
     {
        id: 'comment4',
        text: "Can't wait for the alumni meet!",
        authorId: '4',
        postId: 'post3',
        createdAt: new Date('2024-07-25T19:00:00Z'),
        author: mockUsers[3],
    }
]
